dist: xenial
language: python
branches:
  only:
    - master
python:
  - 3.7
install:
  - pip install -U pip
  - pip install pipenv
  - pip install sphinx_rtd_theme
  - pipenv install
  - export PATH="./bin:$PATH"
script:
  - skip
stages:
  - deploy
jobs:
  include:
    - stage: deploy
      name: Deploy to GitHub Pages
      script: pipenv run make html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        local_dir: build/html